"use client";
export type Thread = { id: string; peerName?: string };
export type ChatMessage = { id: string; from: string; ts: string; type?: string; text?: string };
export const slugify = (s:string)=> (s||"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)+/g,"");
export const nowClock = ()=> new Date().toISOString();
export const loadThreads = ():Thread[] => [];
export const upsertThreadForPeer = (name:string)=>({ id:"thr_"+slugify(name), peerName:name });
export const appendMessage = (..._a:any[])=>{};
export const appendOfferMessage = (..._a:any[])=>{};
export const updateOfferInThread = (..._a:any[])=>{};
export const resetAllChatData = ()=>{};
